// Generated by CoffeeScript 1.6.3
(function() {
  var flutterDown;

  flutterDown = function() {
    var left, offset, top;
    offset = $("#sakura").offset();
    top = offset.top + 1 > $(window).height() ? 0 : offset.top + 1;
    left = offset.left - 1 < 0 ? $(window).width() : offset.left - 1;
    $("#sakura").offset({
      top: top,
      left: left
    });
    return requestAnimationFrame(flutterDown);
  };

  requestAnimationFrame(flutterDown);

}).call(this);
