// Generated by CoffeeScript 1.6.3
(function() {
  var appendSakura, flutterDown, updatePosition;

  flutterDown = function(sakuras) {
    var sakura, _i, _len;
    for (_i = 0, _len = sakuras.length; _i < _len; _i++) {
      sakura = sakuras[_i];
      updatePosition(sakura);
    }
    return requestAnimationFrame(function() {
      return flutterDown(sakuras);
    });
  };

  updatePosition = function(sakura) {
    var left, offset, top;
    offset = sakura.offset();
    if (offset.top + 1 > $(window).height() || offset.left - 0.1 < 0) {
      top = 0;
      left = Math.floor(Math.random() * $(window).width());
    } else {
      top = offset.top + 1;
      left = offset.left - 0.1;
    }
    return sakura.offset({
      top: top,
      left: left
    });
  };

  appendSakura = function() {
    return $('<div class="sakura">').appendTo($('body')).css({
      position: "relative",
      top: Math.floor(Math.random() * $(window).height()),
      left: Math.floor(Math.random() * $(window).width())
    });
  };

  $(function() {
    var sakuras;
    sakuras = (function() {
      var _i, _results;
      _results = [];
      for (_i = 1; _i <= 10; _i++) {
        _results.push(appendSakura());
      }
      return _results;
    })();
    return requestAnimationFrame(function() {
      return flutterDown(sakuras);
    });
  });

}).call(this);
